# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# We need to be able to reclone the repo so it can't be shallow
git:
  depth: false

env:
  matrix:
    include:
      - php: 7.1
        env: GENERATE_COVERAGE="0"
      - php: 7.2
        env: GENERATE_COVERAGE="1"
      - php: hhvm
        env: GENERATE_COVERAGE="0"

matrix:
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [[ ${GENERATE_COVERAGE} == "0" ]]; then phpenv config-rm xdebug.ini; fi
  - composer config github-oauth.github.com ${GITHUB_TOKEN}
  - git config github.accesstoken ${GITHUB_TOKEN}
  - composer config --global github-protocols https

script: bash -x .travis.bash

after_success:
  - if [[ ${GENERATE_COVERAGE} == "1" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ ${GENERATE_COVERAGE} == "1" ]]; php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/var/qa/phpunit_coverage.clover; fi

notifications:
  slack:
    on_success: change
    rooms:
      - secure: eghR0aH9caD9hUsxEqTcSq3r/5JAG+7c5NGTGtNu06iegnh2UDNj1Et20zfvnAEiBlHe+xp9+wtTQZaM/8H/9BheEodKGnsgRxtw3PDeHXXI0GsFCTur4QOuMAHrtrRPDgGrIh7TXrdvbRyk2R09H6PuOqQDl9Nu7GP4qwAJP9R6WAYBD247iS45zeeIpxfkGe+i0uTCMoIrFyKlIJCiVN4DqN4VjzoVxbLinQGJmSc9yJ+Ga07IOvwx0va44aqDxncSi9aNvQ9qZnrgQJJruSX4+HCwKuEVwTbwPvEMFGWlNIj1maGpIkbO8eC2YjDOH/NYwNKlEnSZFNBaYFdXyZW52LyzCCG+sbgggoWZ1mcPh+DOBqPqx9qXH+loHSIk4O3HMbSksjJ/jNO8pbX4vvl82MPM7FEpuHFHlUfr3eZZdBBiYKxIax6nn/F2/uWKHTIUVbcWmeUUmOdqeYeZ/XDgsHGccWvVkxygtlmCGQpinxn6HxajRam828v6kKEJGCDPorIN7OmOuISXhuysyHGlTDDFituJzvxk50vPlKKB+4f+E6vYd1HvAQo0VQVLpFgeO9wCHUDWJ/kQex0qnoE58kY2pLbHP5jrSxZoYZ6r1j7Wq/DFEq2OFxS0uwH+fJYTeJpl28WdW28a0BGNe5Ib/tFQf7o6f25gVAWuqu8=
