<?php declare(strict_types=1);

namespace EdmondsCommerce\DoctrineStaticMeta\CodeGeneration;

class CodeHelper
{

    /**
     * Fix niggles with code that is generated by gossi/php-code-generator
     *
     * @param string $generated
     *
     * @return string
     */
    public function postProcessGeneratedCode(string $generated): string
    {
        $generated = preg_replace('%^([ ]+)?const%', '$1public const', $generated);
        $generated = str_replace('SuppressWarnings (', 'SuppressWarnings(', $generated);

        return $generated;
    }
}
